<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Домашний сайт на домашнем хостинге</title>
    <?=$this->headLink()->appendStylesheet('/extjs/resources/css/ext-all.css')
        ->appendStylesheet('/prettify/prettify.css')?>
    <?=$this->headScript()->appendFile('/extjs/bootstrap.js')
        ->appendFile('/prettify/prettify.js')?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12831189-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body onload="prettyPrint()">
<!-- Yandex.Metrika counter --><div style="display:none;"><script type="text/javascript">(function(w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter1890562 = new Ya.Metrika({id:1890562, clickmap:true, trackLinks:true, webvisor:true}); } catch(e) { } }); })(window, "yandex_metrika_callbacks");</script></div><script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script><noscript><div><img src="//mc.yandex.ru/watch/1890562" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
<script language="javascript" type="text/javascript">
Ext.onReady(function() {
    Ext.define('topDir', {
		extend: 'Ext.data.Model',
		fields: ['id', 'text', 'children'],
		hasMany: 'subDir'
	});
	Ext.define('subDir', {
		extend: 'Ext.data.Model',
		fields: ['id', 'text'],
		belongsTo: 'topDir'
	});

	var treeArticlesStore = Ext.create('Ext.data.TreeStore', {
		model: 'topDir',
		autoLoad: true,
		proxy: {
        	type: 'ajax',
        	url : '/ajax/treeArticles',
        	// Передаем идентификатор текущей статьи для раскрытия дерева в нужном месте
        	extraParams: {
        	    articleID: window.location.pathname
        	},
        	reader: {
            	type: 'json',
            	root: 'children',
            	idProperty: 'id'
        	}
    	},
    	root: {
    		expanded: true,
    		text: '/'
    	}
	});

	var treeArticles = Ext.create('Ext.tree.Panel', {
		store: treeArticlesStore,
		height: 9999,
		listeners: {
			select: function(rowModel, dataModel, row, obj) {
			    if (dataModel.get('leaf')) {
                    window.location.href = '/article/' + dataModel.get('id');
			    }
			}
		}
	});

	var linksBar = Ext.create('Ext.toolbar.Toolbar', {
	    xtype: 'button',
	    items: {
	        text: 'Главная',
	        handler: function() {
	            window.location.href = 'http://' + window.location.host;
	        }
	    }
	});

    var viewport = Ext.create('Ext.container.Viewport', {
    	layout: 'border',
    	items: [{
    	    region: 'north',
    	    items: linksBar
    	},{
            region: 'west',
            layout: 'accordion',
            itemId: 'westMenuPanel',
            width: 250,
            layoutConfig: {
                titleCollapse: false,
                animate: true,
                activeOnTop: true
            },
                items: [{
                    title: 'Дерево блога',
                    items: treeArticles
            	},{
            	    title: 'Облако тегов',
            	    html: '<?=$this->layout()->tags?>'
            	},{
            	    title: 'Контактная информация',
            	    html: '<?=$this->layout()->contacts?>'
            	}]
    	},{
            region: 'center',
            itemId: 'centerMenuPanel',
            autoScroll: true,
            style: {
                marginLeft: '4px',
                marginRight: '2px'
            },
            items: {
                title: '<?=$this->layout()->articleHeadline?>',
                html: '<?=$this->layout()->articleContent?>'
            }
    	}]
    });

    // Раскраска синтаксиса
    prettyPrint();
});
</script>
</body>
</html>