<?=$this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?=$this->headTitle()?>
  <?=$this->headLink()->appendStylesheet('/extjs/resources/css/ext-all.css')
  						->appendStylesheet('/css/admin.login.css')?>
  <?=$this->headScript()->appendFile('/extjs/bootstrap.js')
  						->appendFile('/js/adminLogin.js')?>
</head>
<body><?=$this->layout()->content?></body>
</html>