<script language="javascript" type="text/javascript">
Ext.onReady(function() {

	var loadMaskGrid = new Ext.LoadMask(
	    Ext.getBody(),
	    {
	        msg: 'Пожалуйста, подождите. Идет загрузка ...'
	    });

	function folderFormat(f)
	{
		if (f == 0) return 'файл/статья';
        if (f == 1) return 'папка';
	}

	Ext.define('dataModel', {
	   	extend: 'Ext.data.Model',
	   	fields: [
			{name: 'id', type: 'integer'},
			{name: 'sequence', type: 'integer'},
			{name: 'folder', type: 'string'},
			{name: 'parent', type: 'string'},
			{name: 'name', type: 'string'}
		]
	});

	var store = new Ext.data.Store({
		autoLoad: true,
		model: 'dataModel',
        proxy: {
        	url : '/admin/categoriesView',
        	type: 'ajax',
        	reader: {
        		type: 'json',
        		root: 'categories'
        	}
        }
	});

	var grid = Ext.create('Ext.grid.Panel', {
		title: 'Редактирование категорий/подкатегорий сайта',
		loadMask: loadMaskGrid,
		store: store,
		columns: [
			{header: 'id', dataIndex: 'id'},
			{header: 'порядок', dataIndex: 'sequence'},
			{header: 'тип данных', dataIndex: 'folder', renderer: folderFormat},
			{header: 'родитель', dataIndex: 'parent'},
			{header: 'имя', dataIndex: 'name'}
		]
	});

	Ext.create('Ext.container.Viewport', {
		renderTo: Ext.getBody(),
		xtype: 'grid',
		items: [{
			region: 'center',
			items: grid
		},{
			region: 'west'
		}]
	});
});
</script>