<script language="javascript" type="text/javascript">
Ext.onReady(function() {
    // Плохо что здесь значения меняются и приходится конвертировать обратно
    function userStatus(status, record) {
        var block = 'Блокирован';
        var active = 'Активен';
        if (status == 0) return block;
        if (status == 1) return active;
        if (status == block) return 0;
        if (status == active) return 1;
        return status;
    };

    var loadMaskGrid = new Ext.LoadMask(
        Ext.getBody(),
        {
            msg: 'Пожалуйста, подождите. Идет обмен данными с сервером  ...'
        });

    Ext.define('usersModel', {
        extend: 'Ext.data.Model',
        fields: [
            {name: 'login', type: 'string'},
            {name: 'role', type: 'string'},
            {name: 'enabled', type: 'integer', convert: userStatus},
            {name: 'create'},
            {name: 'change'}
        ]
    });

    var usersStore = Ext.create('Ext.data.Store', {
        autoLoad: true,
        model: 'usersModel',
        proxy: {
            type: 'ajax',
            url: '/ajax/usersView',
            actionMethods: 'POST',
            reader: {
                type: 'json'
            }
        },
        listeners: {
            'update': function(obj, record, operation, opt) {
                loadMaskGrid.show();
                Ext.Ajax.request({
                    url: '/ajax/usersEdit',
                    method: 'POST',
                    params: {
                        login: record.data['login'],
                        role: record.data['role'],
                        enabled: userStatus(record.data['enabled'])
                    },
                    success: function(answer) {
                    },
                    failure: function() {
                        Ext.Msg.alert("Ошибка", 'Не удалось обновить данные пользователя');
                    },
                    callback: function() {
                        loadMaskGrid.hide();
                    }
                });
            }
        }
    });

    var usersGrid = Ext.create('Ext.grid.Panel', {
        title: 'Список всех пользователей зарегистрированных в системе',
        store: usersStore,
        forceFit: true,
        autoScroll: true,
        columns: [
            {header: 'ЛОГИН', dataIndex: 'login'},
            {header: 'РОЛЬ', dataIndex: 'role', editor: {
                    typeAhead: true,
                    xtype: 'combobox',
                    store: [
                        ['guest', 'Гость'],
                        ['staff', 'Персонал'],
                        ['administrator', 'Администратор']
                    ]
            }},
            {header: 'СТАТУС', dataIndex: 'enabled', editor: {
                    typeAhead: true,
                    xtype: 'combobox',
                    store: [
                        [0, 'Заблокировать пользователя'],
                        [1, 'Активировать пользователя']
                    ]
            }},
            {header: 'СОЗДАН', dataIndex: 'create'},
            {header: 'ИЗМЕНЕН', dataIndex: 'change'}
        ],
        selType: 'cellmodel',
        plugins: [
            Ext.create('Ext.grid.plugin.CellEditing', {
                clicksToEdit: 2
            })
        ]
    });

    var statistics = Ext.create('Ext.container.Container', {
        layout: {
            type: 'table',
            columns: 2
        },
        items: [
            {
                html: 'ПОЛЬЗОВАТЕЛИ',
                colspan: 2,
                style: {
                    textAlign: 'center',
                    fontWeight: 'bold'
                }
            },{
                html: 'Всего',
                width: 150
            },{
                html: '<?=$this->cntAll;?>',
                width: 50,
                style: {
                    textAlign: 'right',
                }
            },{
                html: 'Администраторов'
            },{
                html: '<?=$this->cntAdministrator;?>',
                style: {
                    textAlign: 'right',
                }
            },{
                html: 'Персонала'
            },{
                html: '<?=$this->cntStaff;?>',
                style: {
                    textAlign: 'right',
                }
            },{
                html: 'Гостей'
            },{
                html: '<?=$this->cntGuest;?>',
                style: {
                    textAlign: 'right',
                }
            },{
                html: 'СОСТОЯНИЕ',
                colspan: 2,
                style: {
                    textAlign: 'center',
                    fontWeight: 'bold'
                }
            },{
                html: 'Активных'
            },{
                html: '<?=$this->cntEnabled;?>',
                style: {
                    textAlign: 'right',
                }
            },{
                html: 'Блокированных'
            },{
                html: '<?=$this->cntDisabled;?>',
                style: {
                    textAlign: 'right',
                }
            }
        ]
    });

    var viewport = Ext.create('Ext.container.Viewport', {
        layout: 'border',
        items: [
        {
            region: 'north',
            items: linksBar // Переменная определена в шаблоне layout-admin-pages.phtml
        },{
            region: 'west',
            itemId: 'westMenuPanel',
            width: 200,
            items: statistics
            //html: 'Общее количество пользователей зарегистрированных на сайте: <?=$this->cntAll;?>. из них администраторов: <?=$this->cntAdministrator;?>, персонала <?=$this->cntStaff;?> и гостей <?=$this->cntGuest;?>. Активированных учетных записей: <?=$this->cntEnabled;?>, заблокированных: <?=$this->cntDisabled;?>'
        },{
            region: 'center',
            itemId: 'centerMenuPanel',
            items: usersGrid
        }]
	});
});
</script>